org.gradle.jvmargs=-Xmx2G
org.gradle.configuration-cache=false

# Change these four lines to build for a different Minecraft version
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT
fabric_api_version=0.146.1+26.1.2
modmenu_version=18.0.0
minecraft_dep=~26.1

mod_version=8.3.0
maven_group=dev.farmprofit
archives_base_name=skyassist
